### ISSUE TITLE
Type signatures in CommandInfo

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/hermit-web#1]
It would useful for input purposes to have the type signature of a HERMIT command returned in a CommandInfo (from the <tt>/commands</tt> request) so that
1. I could determine how many arguments it requires and
2. I can tweak the input screen to make it tailored to the specific command.

**Comment by xich** [comment]
Done in d020d6ef9110c16af3db7696c773e1227a50765b. Note the change to CommandInfo (extra field).

Though, would it be more useful if, rather than a string that looks like a type signature, I gave back a list of argument types and a single result type? Seems it would save you some parsing.

**Comment by RyanGlScott** [comment]
A list of argument types would probably be the more elegant solution, especially since Armatus would avoid having to split a string every time it reads a CommandResponse. Would special consideration be needed for functions [e.g., <tt>(a -> b) -> b</tt>] or arguments with data classes [e.g., <tt>Monad a => m a -> m b -> m b</tt>]?

**Comment by xich** [comment]
HERMIT's command language is first order (no function arguments), so the first case won't happen. Also, the type signatures I can give back are necessarily monomorphic (no type variables or classes), so the second case won't happen either.

I'll go ahead and make the change and post here when its done.

**Comment by xich** [comment]
Done in da6221e35ebb6023984c9310fab476660338b5f3. You'll need the very latest HERMIT.

Let me know if it works... I haven't tested... only compiled. ;-)
