### ISSUE TITLE
CommandLineState change breaks HERMIT-Web

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/hermit-web#10]
Commit <a href="https://github.com/ku-fpg/hermit/commit/ac3ca73c2dd05d545571e753169db65089a31cf5#diff-d054ac1bc71bd1f58c51fdee42aad7a2">ac3ca73c2d</a> in HERMIT changes a <tt>CommandLineState</tt> parameter from <tt>cl_dict</tt> (a <tt>Dictionary</tt>) to <tt>cl_externals</tt> (an <tt>[Environment]</tt>), which currently prevents <tt><a href="https://github.com/ku-fpg/hermit-web/blob/master/src/HERMIT/Web/Actions.hs#L70">HERMIT.Web.Actions</tt></a> from compiliing correctly:

```
[4 of 5] Compiling HERMIT.Web.Actions ( src/HERMIT/Web/Actions.hs, dist/build/HERMIT/Web/Actions.o ) [HERMIT.Dictionary changed]

src/HERMIT/Web/Actions.hs:75:19:
    `cl_dict' is not a (visible) field of constructor `CommandLineState'
```

Is it easy to change the code to use the new <tt>CommandLineState</tt> constructor, or should I just specify an upper version bound on HERMIT for now?

**Comment by xich** [comment]
Fixed in ae05994915be3defbafc67f52703107265eaa245
