### ISSUE TITLE
Flatten.hs Example

### ISSUE THREAD

**Issue by tucker19** [ku-fpg/hermit-web#11]
When doing the Flatten.hs example on line 4 I am getting a Internal Error (500).
I typed:

```
load-as-rewrite "WWA" "WW-Ass-A.hss"
define-rewrite "WWC" "ww-result-AssA-to-AssC WWA"
load-as-rewrite "StrictRepH" "StrictRepH.hss"
binding-of 'flatten
```

I get:

```
Error (500): Internal Server Error
```

This only happens in Hermit-Web. I tried the example in Hermit.
I typed:

```
load-as-rewrite "WWA" "WW-Ass-A.hss"
define-rewrite "WWC" "ww-result-AssA-to-AssC WWA"
load-as-rewrite "StrictRepH" "StrictRepH.hss"
binding-of 'flatten
```

I get:

```
flatten = λ Δ ds -> 
  case ds of wild Δ
    Node l r -> (++) Δ (flatten Δ l) (flatten Δ r)
    Leaf a -> (:) Δ a ([] Δ)
```

**Comment by RyanGlScott** [comment]
Interestingly, I can't even get that example to work on HERMIT (using commit 2d53ae5d96c4324849103275332d612853d44aed):

```
> hermit Flatten.hs Flatten.hss
...
Booting Failure: Error in expression: binding-of 'flatten
Cannot find path: user error (binding-of failed: No matching nodes found.)
module main:HList where
  absH ∷ ∀ a . H a → [a]
  repH ∷ ∀ a . [a] → [a] → [a]
```

I think this may be a separate issue, but worth considering.

**Comment by xich** [comment]
@RyanGlScott You are trying to run the script on the wrong module. The Flatten example has a Main module which imports the HList module. Without specifying, HERMIT will run on both. You need to invoke as:

```
> hermit Flatten.hs +Main Flatten.hs
```

(Older HERMIT always ran on the Main module if no module was specified, but this behavior was changed some time ago.)

@tucker19 Is any error getting dumped to the command line on the server side? Does the Android app pass through the error message attached to the 500 response?

**Comment by RyanGlScott** [comment]
@xich Whoops, using the correct arguments definitely makes a difference.

@tucker19 I'm now having the exact same problem as you, so I'll try to see if I can make Armatus's output for HTTP server code errors more verbose in order to figure out what's going on. It doesn't appear to be an error with the way special characters (e.g., the single quote in <tt>'flatten</tt>) are put into JSON, since I can call <tt>binding-of 'last</tt> while using <tt>hermit-web Last.hs</tt> just fine.

**Comment by tucker19** [comment]
@RyanGlScott This is the first example I have ran into a problem with binding-of 'anything. All the other examples I have done with binding-of have worked fine.

**Comment by RyanGlScott** [comment]
Unfortunately, the Java stracktrace doesn't really illuminate anything:

```
978  25391-25425/edu.kufpg.armatus W/System.err﹕ org.apache.http.HttpException: Error code 500
04-28 16:17:01.008  25391-25425/edu.kufpg.armatus W/System.err﹕ at edu.kufpg.armatus.networking.HermitHttpServerRequest.doInBackground(HermitHttpServerRequest.java:96)
04-28 16:17:01.018  25391-25425/edu.kufpg.armatus W/System.err﹕ at edu.kufpg.armatus.console.HermitClient$7.doInBackground(HermitClient.java:471)
04-28 16:17:01.018  25391-25425/edu.kufpg.armatus W/System.err﹕ at edu.kufpg.armatus.console.HermitClient$7.doInBackground(HermitClient.java:467)
04-28 16:17:01.018  25391-25425/edu.kufpg.armatus W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
04-28 16:17:01.018  25391-25425/edu.kufpg.armatus W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-28 16:17:01.018  25391-25425/edu.kufpg.armatus W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-28 16:17:01.028  25391-25425/edu.kufpg.armatus W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-28 16:17:01.028  25391-25425/edu.kufpg.armatus W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-28 16:17:01.028  25391-25425/edu.kufpg.armatus W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
```

**Comment by tucker19** [comment]
Trying this with curl.

Typed:

```
curl http://localhost:3000/command -X POST -H "content-type: application/json" -d "{\"token\":{\"user\":0,\"ast\":0},\"cmd\":\"binding-of 'flatten\"}"
```

Get:

```
{"msg":"Error in expression: binding-of 'flatten\nCannot find path: user error (binding-of failed: No matching nodes found.)"}
```

**Comment by xich** [comment]
Are you invoking hermit-web on the right module? If `binding-of` can't find flatten, I'm guessing that you are trying to run the script on the `HList` module.

**Comment by RyanGlScott** [comment]
Ah, I think it may be a matter of HERMIT-Web's executable not passing command-line arguments (namely, <tt>Flatten.hs +Main Flatten.hss</tt>) to HERMIT. <a href="https://github.com/ku-fpg/hermit-web/blob/master/driver/Main.hs#L11">These lines</a> in particular from the driver code seem suspect:

```
main :: IO ()
main = do
    (file_nm:_) <- getArgs -- TODO: real option parser
    putStrLn $ "[starting " ++ hermit_version ++ " web service on " ++ file_nm ++ "]"

    let cmds = file_nm : ghcFlags ++ plugin_cmds
        plugin_cmds = ["-fplugin=HERMIT.Web"
                      ,"-package ghc"]
    putStrLn $ "% ghc " ++ unwords cmds
    ex <- runWithArgs "ghc" cmds
    exitWith ex
```

It looks like when <tt>hermit-web Flatten.hs +Main Flatten.hss</tt> is called, it ignores everything after <tt>hermit-web Flatten.hs</tt>. Could this be fixed by something along the lines of:

```
(file_nm:hermit_args) <- getArgs -- TODO: real option parser
putStrLn $ "[starting " ++ hermit_version ++ " web service on " ++ file_nm ++ "]"

let cmds = file_nm : hermit_args ++ ghcFlags ++ plugin_cmds
...
```

**Comment by RyanGlScott** [comment]
Actually, the code I suggested would pass <tt>Flatten.hs +Main Flatten.hss</tt> directly to GHC, which definitely wouldn't work. Would it be sufficient to just use <a href="https://github.com/ku-fpg/hermit/blob/master/driver/Main.hs">the same argument-parsing code</a> that HERMIT's driver program uses, or are there more subtleties to consider?

**Comment by xich** [comment]
This is hopefully fixed in d8009fd617b8d0493daa099835d70ad60ae301f5 (you'll need to pull the latest HERMIT from github as well).

Please test and close the ticket if it works!

**Comment by RyanGlScott** [comment]
I'm now getting the expected output from <tt>curl</tt>, so I think it worked. Thanks Andrew!

**Comment by xich** [comment]
Thanks for tracking down the real problem. That made the fix pretty easy.

**Comment by robfblair** [comment]
Gethrff.fvayhf_&1$4fgl&&-)&(--&(5_-&3.3J UIUJ

-----Original Message-----
