### ISSUE TITLE
Improvements to glyph paths

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/hermit-web#2]
To make it easier to identity the scoping of a glyph, it would be nice to have its "parent" glyph included in the path of each glyph (so that, for instance, I could draw connecting lines between a glyph and its "child" glyphs).

Another idea is to only include relative paths for each glyph (so as to eliminate redundant information), but I'm not sure if this conflicts with the previous idea.

**Comment by xich** [comment]
Glyphs which represent variable occurences now have a `bindingSite` attribute with an absolute path to the binding site. This should facilitate arrows in the GUI.

child->parent: arrow from current glyph to glyph at `bindingSite` path
parent->children: arrow from current glyph to all glyphs which have `bindingSite` set to path of current glyph

I haven't done the relative path bit yet, as it will require a bit more computation on the client side... are you sure you want this?

**Comment by RyanGlScott** [comment]
To be honest, I'm not sure whether the relative paths are totally necessary or not. I was under the impression that it would help facilitate selecting subexpressions from a CommandResponse, although this may be possible with the current setup. The other benefit of relative paths would be not needing to serialize as much data in the app itself (which happens frequently, due to screen rotations and device standby), although the amount of storage needed for text is certainly less taxing than, say, images, so this may not be a limiting factor either.

**Comment by RyanGlScott** [comment]
It turns out that relative paths aren't necessary, so I'll close this issue.
