### ISSUE TITLE
CommandInfo's types incorrect for functions with at least two arguments

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/hermit-web#5]
<tt>/commands</tt> is not returning the correct result for functions that have at least two argument types. For example, the types that HERMIT-Web gives for <tt>fix-fusion-rule</tt> are currently:

```
"resTy":"Core -> Core -> RewriteCore -> RewriteCore -> RewriteCore -> BiRewriteCore","argTys":["Core"]
```

I believe it should actually be:

```
"resTy":"BiRewriteCore","argTys":["Core","Core","RewriteCore","RewriteCore","RewriteCore"]
```

**Comment by xich** [comment]
Oops, sorry... this is fixed (in latest HERMIT).
