### ISSUE TITLE
Indentation width calculator

### ISSUE THREAD

**Issue by RyanGlScott** [ku-fpg/hermit-web#6]
Implement a function that, when given the number of characters per line (assuming a monospaced font), will return the optimal indentation for a command response. I don't know if this could be integrated into `/command` or if it should be separated into its own POST request.

**Comment by xich** [comment]
This is (hopefully, please test) done in 81d91e01dbccf791d62fbe26b1d018505aa0e798

Command's now have an optional 'width' field, which is the width of the screen in characters. HERMIT is stateful enough to keep the last used width and re-use it, but it is best practice to send it with every request. If you want to re-render the current AST without running a rewrite on it, call the 'display' command with the new width. I imagine in the Android app, you'll want a combination of zooming (while the touch resizing is happening, so the UI is smooth) and re-rendering via HERMIT (once the touch event ends and a new size is calculated).
