### ISSUE TITLE
binding-of not working

### ISSUE THREAD

**Issue by tucker19** [ku-fpg/hermit-web#8]
I listened to you last week when you said consider is no longer useable and to move to binding-of. I am getting a error 500 when I try binding-of. I am also getting a error when running binding-of in regular hermit.

**Comment by RyanGlScott** [comment]
Are you using the most recent version of HERMIT? It seems to be working fine for me:

```
$ hermit Last.hs
...
module main:Main where
  last ∷ ∀ a . [a] → a
  wrap ∷ ∀ a . (a → [a] → a) → [a] → a
  unwrap ∷ ∀ a . ([a] → a) → a → [a] → a
  main ∷ IO ()
  main ∷ IO ()
hermit<0> help binding-of
binding-of :: String -> TranslateCoreTCPath                       [Navigation]
  Find the path to the binding of the named variable.

hermit<0> binding-of last
last = λ △ ds →
  case ds of wild ▲
    [] → undefined ▲
    (:) a ds →
      case ds of wild ▲
        [] → a
        (:) a as → last ▲ ((:) ▲ a as)
```

**Comment by tucker19** [comment]
fixed, I didnt have the most up to date version off of here and not hackage.
