### ISSUE TITLE
There is no package named 'hermit-web'

### ISSUE THREAD

**Issue by tucker19** [ku-fpg/hermit-web#9]
When I do a git pull from the repo and then cabal install hermit-web --reinstall I get an error "There is no package named 'hermit-web'.

**Comment by andygill** [comment]
What do you type? Have you tried

```
$ cabal install 
```

or

```
$ cabal install --reinstall
```

from inside the repo?

**Comment by tucker19** [comment]
I am inside the repo directory and I have typed cabal install hermit-web --reinstall. In the past anytime I have had to do this I have to specify the name but I will try just cabal install --reinstall

**Comment by tucker19** [comment]
the cabal install --reinstall worked. I tried to open a .hs file with hermit web and got this error:
Loading package hermit-web-0.1.0.0 ... linking ... ghc: 
lookupSymbol failed in relocateSection (relocate external)
/Users/AdamHowell/Library/Haskell/ghc-7.6.3/lib/hermit-web-0.1.0.0/lib/HShermit-web-0.1.0.0.o: unknown symbol `_scottyzm0zi6zi2_WebziScottyziTypes_zdfIsStringRoutePatternzuouter_info'
ghc: unable to load package`hermit-web-0.1.0.0'

**Comment by andygill** [comment]
Look at the above example of how to report what you did in a way that allows others to reproduce what you did.  "I tried to open" should be replaced with 

I typed

```
$ ghc A.B -XABC
```

And I got

```
ABCDEF Bla Bla
```

as an error message. (Indent by 4 spaces to get the markdown to say this)

**Comment by andygill** [comment]
And where is dictionaries.hs? We can't _guess_, we need to be reproduce the problem.

**Comment by tucker19** [comment]
I typed within the hermit directory

```
$ cd examples/Dictionaries
$ hermit-web dictionaries.hs
```

and I got 

```
Loading package hermit-web-0.1.0.0 ... linking ... ghc: 
lookupSymbol failed in relocateSection (relocate external)
/Users/AdamHowell/Library/Haskell/ghc-7.6.3/lib/hermit-web-0.1.0.0/lib/HShermit-web-0.1.0.0.o: unknown symbol _scottyzm0zi6zi2_WebziScottyziTypes_zdfIsStringRoutePatternzuouter_info'
ghc: unable to load package
```

**Comment by xich** [comment]
A couple things:
- If you specify the name of a package like so:

```
cabal install foo-package
```

It will try to download the package from hackage. This is why it couldn't find the `hermit-web` package earlier... because `hermit-web` is not on hackage. If you are in the project directory, you just need to type `cabal install` (and if you want a totally fresh build, `cabal clean` first).
- Given that error, I'm guessing you have an out-of-date `hermit-web` binary somehow. I just tried things and they worked for me. Can you:

```
which hermit-web
```

and then delete that file? I'm guessing the path will be `~/.cabal/bin/hermit-web`, but use whatever path `which` tells you. Then do a re-install (see next bullet point).
- At the moment, `hermit-web` works with the hackage-uploaded versions of both Scotty and HERMIT. So to get a clean slate:

```
ghc-pkg unregister scotty --force
ghc-pkg unregister hermit --force
ghc-pkg unregister hermit-web --force
cd /path/to/hermit-web/repo
cabal update
cabal clean
cabal install
```

Should install everything for you. (Scotty 0.7.1 and HERMIT 0.4.0.0)

**Comment by tucker19** [comment]
thank you for the install issue. Now it is the error I am getting while trying to actually run hermit-web.
I typed within the hermit directory

```
$ cd examples/Dictionaries
$ hermit-web dictionaries.hs
```

and I got 

```
Loading package hermit-web-0.1.0.0 ... linking ... ghc: 
lookupSymbol failed in relocateSection (relocate external)
/Users/AdamHowell/Library/Haskell/ghc-7.6.3/lib/hermit-web-0.1.0.0/lib/HShermit-web-0.1.0.0.o: unknown symbol _scottyzm0zi6zi2_WebziScottyziTypes_zdfIsStringRoutePatternzuouter_info'
ghc: unable to load package
```

**Comment by tucker19** [comment]
Andrew, I tried the the second built point you put up.
I typed:

```
    $ which hermit-web
```

Got:

```
    /Users/AdamHowell/Library/Haskell/bin/hermit-web
```

I am not for sure if that is the correct. I did Also look up my hermit to see where that was. Thought it would also be a good idea to see if hermit was working and it is.
Typed:

```
    $ which hermit 
```

Got:

```
    /usr/bin/hermit
```

I also went through your bullet points and did everything. After the clean install I am still getting the same error.

```
    Loading package hermit-web-0.1.0.0 ... linking ... ghc: 
    lookupSymbol failed in relocateSection (relocate external)
    /Users/AdamHowell/Library/Haskell/ghc-7.6.3/lib/hermit-web-0.1.0.0/lib/HShermit-web-0.1.0.0.o: unknown symbol _scottyzm0zi6zi2_WebziScottyziTypes_zdfIsStringRoutePatternzuouter_info'
    ghc: unable to load package
```
